package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u331/2416/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, March 10, 2022 11:14:10 AM GMT
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
  	 * The value representing ID_UNIQUENESS_POLICY_ID.
  	 */
  public static final int value = (int)(18L);
}
